#!/usr/bin/env python
import pygame

SCREEN_WIDTH = 2560
SCREEN_HEIGHT = 1080

BG_COLOR = (0, 0, 20)
PLAYER_COLOR = (255, 255, 50)
AI_COLOR = (0, 50, 250)
INFECTED_COLOR = (255, 0, 0)

REFRESH_DELAY = 15
INIT_ACTORS = 30
MAX_ACTORS = 100

GENERATION_INTERVAL = 200
GENERATION_PROB = 0.50
MOVE_INTERVAL = 100
MOVE_PROB = 0.25
INFECTION_INTERVAL = 50
INFECTION_PROB = 0.75
KILL_INTERVAL = 1000
KILL_PROB = 0.20


global SURFACE_MAIN, PLAYER
SURFACE_MAIN = None
PLAYER = None

global ACTORS, AI_ACTORS, HEALTHY, INFECTED
ACTORS = pygame.sprite.Group()
AI_ACTORS = pygame.sprite.Group()
HEALTHY = pygame.sprite.Group()
INFECTED = pygame.sprite.Group()
